//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MyPos.rc
//
#define IDC_BUTTON_RF                   3
#define IDC_BUTTON_OFFPRINT             3
#define IDC_BUTTON_HANG                 4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MYPOS_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_BASE                 129
#define IDD_DIALOG_CLASS                130
#define IDD_DIALOG_POS                  131
#define IDD_DIALOG_STAT                 132
#define IDD_DIALOG_MATERIEL             133
#define IDD_DIALOG_PAYMODE              134
#define IDD_DIALOG_SYSMT                135
#define IDD_DIALOG_USER                 136
#define IDD_DIALOG_LOGON                138
#define IDD_DIALOG_SYSSET               141
#define IDD_DIALOG_SELECT               143
#define IDD_DIALOG_MODIFYQA             144
#define IDD_DIALOG_CALL                 145
#define IDD_DIALOG_CHECK                146
#define IDB_SPLASH                      147
#define IDB_LOGO                        149
#define IDD_DIALOG_CLEAR                152
#define IDD_DIALOG_OFFDUTY              153
#define IDI_ICON1                       179
#define IDD_DIALOG1                     183
#define IDC_TAB1                        1000
#define IDC_TAB_BASE                    1001
#define IDC_TREE_CLASS                  1002
#define IDC_EDIT_CLASSNAME              1003
#define IDC_BUTTON_ADDSAME              1005
#define IDC_BUTTON_ADDSUB               1006
#define IDC_TREE_MCLASS                 1006
#define IDC_BUTTON_DEL                  1007
#define IDC_LIST_MATERIEL               1007
#define IDC_BUTTON_SAVE                 1008
#define IDC_EDIT_MNAME                  1008
#define IDC_EDIT_MPRICE                 1009
#define IDC_EDIT_MSHOPCODE              1010
#define IDC_EDIT_MBARCODE               1011
#define IDC_CHECK_SUPPLY                1014
#define IDC_BUTTON_MADD                 1015
#define IDC_BUTTON_MDEL                 1016
#define IDC_BUTTON_MSAVE                1017
#define IDC_COMBO_MDISCOUNT             1018
#define IDC_LIST_PAYMODE                1019
#define IDC_BUTTON_PADD                 1020
#define IDC_BUTTON_PDEL                 1021
#define IDC_TAB_SYSMT                   1021
#define IDC_LIST_USER                   1022
#define IDC_BUTTON_PADD2                1022
#define IDC_EDIT_USERNAME               1023
#define IDC_EDIT_DUTY                   1024
#define IDC_COMBO_SEX                   1025
#define IDC_EDIT_DATEBIRTH              1026
#define IDC_EDIT_JIGUAN                 1027
#define IDC_EDIT_NUMBER                 1028
#define IDC_EDIT_DISCOUNT               1029
#define IDC_BUTTON_UADD                 1030
#define IDC_EDIT_LOGNAME                1031
#define IDC_EDIT_PWD                    1032
#define IDC_EDIT_LOGPWD                 1032
#define IDC_BUTTON_UDEL                 1033
#define IDC_BUTTON_USAVE                1034
#define IDC_COMBO_LOGON                 1034
#define IDC_RADIO1_DISCOUNT             1036
#define IDC_RADIO2_DISCOUNT             1037
#define IDC_TEMPID                      1039
#define IDC_EDIT_USERID                 1040
#define IDC_EDIT_PAYMODE                1041
#define IDC_STATIC_SHOWHINT             1042
#define IDC_BUTTON_SAVESET              1043
#define IDC_EDIT_FLOORNUMBER            1044
#define IDC_EDIT_RESNAME                1045
#define IDC_EDIT_TABLENO                1046
#define IDC_EDIT_CKECK                  1047
#define IDC_EDIT_PEASONS                1048
#define IDC_EDIT_STATUS                 1049
#define IDC_EDIT_BEGINTIME              1050
#define IDC_EDIT_ENDTIME                1051
#define IDC_EDIT_TOTAL                  1053
#define IDC_EDIT_FDISCOUNT              1054
#define IDC_EDIT_ACTTOTAL               1055
#define IDC_BUTTON_OFF                  1056
#define IDC_BUTTON_ADDF                 1057
#define IDC_BUTTON_CALLF                1059
#define IDC_BUTTON_HIDEF                1060
#define IDC_BUTTON_CHECKF               1061
#define IDC_BUTTON_FINDF                1062
#define IDC_BUTTON_CASHBOX              1063
#define IDC_BUTTON_LOCALP               1064
#define IDC_BUTTON_KITCHENP             1065
#define IDC_LIST_BILL                   1066
#define IDC_BUTTON_DELF                 1068
#define IDC_TREE_SCLASS                 1069
#define IDC_BUTTON_SADD                 1071
#define IDC_LIST_SELECT                 1072
#define IDC_LIST_FORM                   1073
#define IDC_BUTTON_SELMATERIEL          1074
#define IDC_EDIT_MODIFYQA               1075
#define ID_MOK                          1076
#define ID_MCANCEL                      1077
#define IDC_EDIT_CALLBILLID             1078
#define IDC_BUTTON_CHECKOK              1079
#define IDC_EDIT_WINDD                  1080
#define IDC_EDIT_RECEIVE                1080
#define IDC_EDIT_TOTALM                 1081
#define IDC_EDIT_DISHD                  1082
#define IDC_EDIT_CHANGE                 1082
#define IDC_EDIT_CDISCOUNT              1083
#define IDC_COMBO_PAYMODE               1084
#define IDC_LIST_CHECKLIST              1085
#define IDC_EDIT_CONSUME                1087
#define IDC_RADIO_SINGLE                1088
#define IDC_RADIO_WEEK                  1089
#define IDC_CHECK_TURN                  1090
#define IDC_BUTTON_STAT                 1091
#define IDC_BUTTON_PRINTREPORT          1092
#define IDC_STATIC_REPORT               1094
#define IDC_DATETIMEPICKER_SD           1100
#define IDC_DATETIMEPICKER_OD           1101
#define IDC_EDIT_ST                     1102
#define IDC_EDIT_OT                     1103
#define IDC_LIST_REPORT                 1105
#define IDC_STATIC_USERNAME             1106
#define IDC_STATIC_COMPANY              1107
#define IDC_IMAGE_LOGO                  1108
#define IDC_IMAGE1                      1109
#define IDC_CHECK1                      1110
#define IDC_CHECK2                      1111
#define IDC_DATETIMEPICKER_FROM         1111
#define IDC_CHECK3                      1112
#define IDC_DATETIMEPICKER_TO           1112
#define IDC_CHECK4                      1113
#define IDC_CHECK5                      1114
#define IDC_BUTTON_CLEAR                1114
#define IDC_CHECK6                      1115
#define IDC_EDIT1                       1115
#define IDC_EDIT_CHECKMAN               1115
#define IDC_EDIT_LISTTITLE              1115
#define IDC_CHECK7                      1116
#define IDC_EDIT2                       1116
#define IDC_EDIT_OFFTIME                1116
#define IDC_CHECK8                      1117
#define IDC_LIST1                       1117
#define IDC_CHECK9                      1118
#define IDC_LIST2                       1118
#define IDC_STATIC_CALL                 1118
#define IDC_LIST3                       1119
#define IDC_EDIT3                       1120
#define IDC_EDIT_OFFTOTAL               1120
#define IDC_EDIT_OFFBILLS               1120
#define IDC_EDIT4                       1121
#define IDC_EDIT_OFFPEOPLES             1121
#define IDC_EDIT5                       1122
#define IDC_EDIT_OFFRF                  1122
#define IDC_EDIT6                       1123
#define IDC_EDIT_OFFRFMONEY             1123

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1125
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
